### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by clemenslindner** [OmarShehata/google-earth-as-gltf#5]
It always comes up with this error. I created an API key and clicked on the Fetch files button.

Error:

"Fetching...
Fetching tiles at (40.6892 -74.0445, 17, sse: 8)
Failed to fetch 3D Tiles! Error: Error: Failed to fetch resource https://tile.googleapis.com/v1/3dti..."

**Comment by OmarShehata** [comment]
@clemenslindner please make sure the API key has the right permissions. https://developers.google.com/maps/documentation/tile/get-api-key

https://console.cloud.google.com/google/maps-apis/api-list

![chrome_hM5NJQ5azI](https://github.com/OmarShehata/google-earth-as-gltf/assets/1711126/06951f1b-26d2-4c85-8cb0-a6e09657d06e)
